version: '3.8'

services:
  arango:
    image: arangodb/arangodb
    container_name: arango
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./data:/var/lib/arangodb3
      - ./dataset:/tmp/dataset
